# Text for `site.*`
title: Complete list of all GitHub profile Badges and Achievements
logo_url: https://avatars.githubusercontent.com/u/117988194?s=200&v=4
url: https://badges-and-achievements.github.io/
baseurl: ""
repository: badges-and-achievements/badges-and-achievements.github.io

permalinks: pretty

include:
  - LICENSE

plugins:
  - github-pages
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-sitemap

# Exclude the `vendor` folder created by build process
exclude:
  - vendor

defaults:
  -
    scope:
      path: "index.md"
    values:
      order: 0 # Show the index at the top of the navigation
  -
    scope:
      path: "LICENSE.md"
    values:
      order: 100 # Show the license at the bottom of the navigation

titles_from_headings:
  strip_title: true

syntax_highlighter: rouge
